<a href="https://colab.research.google.com/github/d1jeett/dap-2024/blob/main/les03/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [13]:
import numpy as np

# создаём массив 10x10 со случайными целыми числами от 1 до 100
matrix = np.random.randint(low=1, high=101, size=(10, 10))
print("Массив:\n", matrix)

# находим минимум и максимум
print("Минимум:", np.min(matrix))
print("Максимум:", np.max(matrix))

Массив:
 [[49 35 54 39 91 70 24 53 97 81]
 [49 24 43  6 41  2  9 25 74 16]
 [19 40 13 29 62 95 69 61 38 96]
 [91 84  5 66  7 17 93 39 73 94]
 [29 44 33 23 28 74 41 27 20 66]
 [ 6 47 13 24 43 61 81 10 10 40]
 [66 56 82 87 17 69 96 64 80  9]
 [77 51 14 33 82 77 64 37 48 29]
 [ 4 11 79 73  3 75 98  7 64 41]
 [30 41 81 93 35 89 26 93 31 47]]
Минимум: 2
Максимум: 98


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [14]:
import numpy as np

# создаём матрицу 8x8 в шахматном порядке
matrix = np.zeros((8, 8), dtype=int)
matrix[::2, 1::2] = 1  # чётные строки, нечётные столбцы
matrix[1::2, ::2] = 1  # нечётные строки, чётные столбцы

print("Матрица 8x8 в шахматном порядке:\n", matrix)

Матрица 8x8 в шахматном порядке:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [15]:
import random

# создаём массив из 11 случайных чисел от 0 до 10
arr = [random.randint(0, 10) for _ in range(11)]
print("Исходный массив:", arr)

# меняем знак у элементов между 3 и 8 включительно
for i in range(len(arr)):
    if 3 <= arr[i] <= 8:
        arr[i] = -arr[i]

print("Преобразованный массив:", arr)

Исходный массив: [1, 8, 7, 5, 5, 3, 8, 9, 1, 5, 5]
Преобразованный массив: [1, -8, -7, -5, -5, -3, -8, 9, 1, -5, -5]


4. Найти среднее значение строки матрицы и вычесть его из каждого елемента строки

In [19]:
import numpy as np

z = np.random.rand(5, 10)
print("Исходная матрица:\n", z)

# проходим по каждой строке и вычитаем среднее
for i in range(z.shape[0]):
    row_mean = z[i].mean()
    z[i] = z[i] - row_mean

print("\nМатрица после вычитания среднего каждой строки:\n", z)

Исходная матрица:
 [[0.4639228  0.9668666  0.4688339  0.29901071 0.44155392 0.54512993
  0.09873056 0.38119902 0.733396   0.13335136]
 [0.78261951 0.04634944 0.90721291 0.34060349 0.87806741 0.04777761
  0.36380404 0.24440434 0.77098495 0.50863009]
 [0.61774189 0.0991584  0.11393614 0.45165193 0.91202839 0.68339777
  0.74638802 0.21954183 0.92284018 0.25035725]
 [0.84014789 0.65883638 0.79365003 0.29424919 0.9672341  0.38208346
  0.17244887 0.99375195 0.71992699 0.98882131]
 [0.74837359 0.13314556 0.68674694 0.87925732 0.17462084 0.17691212
  0.87432463 0.95680802 0.84698206 0.2258077 ]]

Матрица после вычитания среднего каждой строки:
 [[ 0.01072332  0.51366712  0.01563442 -0.15418877 -0.01164556  0.09193045
  -0.35446892 -0.07200046  0.28019652 -0.31984812]
 [ 0.29357413 -0.44269594  0.41816753 -0.14844188  0.38902203 -0.44126777
  -0.12524134 -0.24464104  0.28193957  0.01958471]
 [ 0.11603771 -0.40254578 -0.38776804 -0.05005225  0.41032421  0.18169359
   0.24468384 -0.28216235  0.42

5. Поменяйте 1 и 2 строки матрицы

In [20]:
import numpy as np

z = np.arange(25).reshape(5,5)

# Меняем местами 1-ю и 2-ю строки
z[[0, 1]] = z[[1, 0]]

print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [21]:
import numpy as np

# Создаём случайный массив точек 10x2
z = np.random.random((10, 2))

# Преобразуем в полярные координаты
polar = np.array([[np.sqrt(x**2 + y**2), np.arctan2(y, x)] for x, y in z])

print("Декартовы координаты:\n", z)
print("\nПолярные координаты (r, θ):\n", polar)


Декартовы координаты:
 [[0.50828984 0.41981719]
 [0.06408418 0.99826203]
 [0.72350625 0.01684568]
 [0.27785496 0.13963012]
 [0.17815815 0.96840945]
 [0.09733638 0.76450021]
 [0.42753229 0.72905333]
 [0.95058697 0.15378241]
 [0.76327275 0.4635912 ]
 [0.53106572 0.02181252]]

Полярные координаты (r, θ):
 [[0.65924581 0.69035942]
 [1.00031688 1.50668854]
 [0.72370233 0.02327919]
 [0.31096616 0.4656686 ]
 [0.98466095 1.38886079]
 [0.77067174 1.4441574 ]
 [0.84516425 1.04042112]
 [0.9629458  0.1603867 ]
 [0.89302972 0.54582314]
 [0.53151348 0.04105003]]


7. Заменить максимальный элемент массива на ноль

In [22]:
import numpy as np

# Случайный массив из 10 элементов
z = np.random.random(10)
print("Исходный массив:", z)

# Находим индекс максимального элемента
max_index = np.argmax(z)

# Заменяем его на 0
z[max_index] = 0
print("После замены максимального элемента на 0:", z)


Исходный массив: [0.67621944 0.57573736 0.73959122 0.44393231 0.5623548  0.36053853
 0.38065159 0.7730255  0.85297248 0.8138867 ]
После замены максимального элемента на 0: [0.67621944 0.57573736 0.73959122 0.44393231 0.5623548  0.36053853
 0.38065159 0.7730255  0.         0.8138867 ]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [23]:
import numpy as np

# Исходные данные
z = np.ones(10)
i = np.random.randint(0, len(z), 20)

print("Исходный массив z:", z)
print("Массив индексов i:", i)

# Добавляем 1 к каждому элементу z с уникальным индексом из i
z[np.unique(i)] += 1

print("Массив после добавления 1:", z)


Исходный массив z: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Массив индексов i: [3 6 7 6 1 1 6 5 3 8 8 3 0 9 9 4 2 1 0 7]
Массив после добавления 1: [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [25]:
import numpy as np

z = np.array([1, 2, 3, 4, 5])

# Повторяем каждый элемент 4 раза
repeated = np.repeat(z, 4)

# Обнуляем все, кроме первых элементов каждой группы
repeated[1::4] = 0
repeated[2::4] = 0
repeated[3::4] = 0

print(repeated)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


10. Найти ближайшее к заданному значению число в заданном массиве

In [27]:
import numpy as np

z = np.arange(100)          # массив чисел
v = np.random.uniform(0, 100)  # случайное число

# Находим индекс элемента массива, ближайшего к v
index = np.argmin(np.abs(z - v))

# Ближайшее число
nearest = z[index]

print("Случайное число v:", v)
print("Ближайшее число в массиве z:", nearest)


Случайное число v: 42.47326666581374
Ближайшее число в массиве z: 42


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3]) - int64
np.array([1., 4, 2, 5, 3]) - float64
np.array([1, 4, 2, 5, 3], dtype='float128') - float128
np.array([1., 4, 2, 5, 3], dtype='complex128') - complex128
np.array([1, 4, 2, 5, 3], dtype ='float64') - float64
np.array([1, 4, 2, 5, 3], dtype =int64) - int64
np.array([1, 4, 2, 5, 3], dtype='bool') - bool
np.array([1, 4, 2, 5, 3], dtype='str') - <U(cтрока)
np.array([1, 4, 2, 5, '3']) - <U(cтрока)
np.array([1, -4, 2, 0, 1j]) - complex128
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1' / ('41' элемент с индексом 1 приводится к строке '4', прибавляем '1')
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1] / ('-4' массив с dtype=bool: [True, True, True, False, True]; [3] → False; False or -4 даёт первый истинный элемент → -4)
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1] / ('False' [3] → False; False and -4 даёт первый ложный элемент → False.)
np.array([1, -4, 2, 0, True], dtype='int64')[-1] / ('1' True в массиве int64 преобразуется в 1.)
np.array([1, -4, 2, 0, 1j], dtype='int64')[1] / ('TypeError' — нельзя преобразовать 1j в int)
np.array([1, -4, 2, 0, 1j], dtype='str')[-1] / ('1j' комплексное число преобразовано в строку.)
np.array([1, 4, 2, 5, '3'])[-1] * 3 / ('333' — массив содержит строки, последний элемент '3' умножаем на 3 → '333')
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float) / - 3×5 массив, все элементы 1.0
np.full((3, 5), 3.14) / - 3×5 массив, все элементы 3.14
np.linspace(0, 1, 5) / - [0. , 0.25, 0.5 , 0.75, 1. ]
np.diag((1,3,5)) / - диагональная матрица 3×3 с диагональю [1,3,5]
np.smile((1,3,5)) / - AttributeError (нет такой функции)
np.random.random((3, 3)) / - 3×3 массив случайных чисел [0,1)
np.eye(3) / - единичная матрица 3×3
np.empty(3) / - массив длиной 3 с неопределёнными значениями
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0] - 3
X[-1,-1] - 7
X[0:1,-1] - [4]
X[0:2,-1] - [4 8]
X[0:2,0:2] - [[3 5] [7 6]]
X[1,1:3] - [6 8]
X[1,:] - [7 6 8 8]
X[1,:] - [7 6 8 8]
X[:,:] - [[3 5 2 4] [7 6 8 8] [1 6 7 7]]
X[:] - [[3 5 2 4] [7 6 8 8] [1 6 7 7]]
X[::2,::2] - [[3 2] [1 7]]
X[0:3:2,0:3:2] - [[3 2] [1 7]]
X[::-1,::-1] - [[7 7 6 1] [8 8 6 7] [4 2 5 3]]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2]) -  деление по строкам
np.split(grid, [2], axis=1) - деление по столбцам

```

**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1] - конкатенация списков
    np.array([1, 2, 3]) + np.array([3, 2, 1]) - поэлементное сложение массивов
```

**7**. Как в CodeLab измерить время выполнения кода?

```python
import time

# Способ 1: time.time()
start = time. Time()
# ваш код
end = time.time()
print(f"Время выполнения: {end - start:.6f} секунд")

# Способ 2: time.perf_counter() (более точный)
start = time.perf_counter()
# ваш код
end = time.perf_counter()
print(f"Время выполнения: {end - start:.6f} секунд")

# Способ 3: магия Jupyter (если в ноутбуке)
%%timeit
# ваш код
```


**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M) - 64
np.sum(M, axis=1) - [14, 29, 21]
np.sum(M, axis=0) - [11, 17, 17, 19]
np.sum(M, axis=2) - Ошибка
np.sum(M, 1) - [14, 29, 21]
sum(M) - [11, 17, 17, 19]
sum(M,1) - ошибка
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
[false false false true]
X < 3
[true true false false]
X[X < 3]
[1 2]
X[X > 3]
[4]
X[X != 3]
[1 2 4]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?

Преимущества массивов NumPy по сравнению с обычными списками Python:

Быстродействие – операции выполняются намного быстрее, особенно над большими массивами.

Эффективное использование памяти – элементы хранятся компактно в виде однотипных блоков.

Векторизация – поддерживаются поэлементные операции без явных циклов (+, *, сравнения и т.д.).

Удобство работы с многомерными данными – матрицы, тензоры, срезы, транспонирование и др.

Большое количество готовых функций – линейная алгебра, статистика, генерация случайных чисел и т.п.

Причина преимущества:

NumPy реализован на C, использует однородные типы данных и континуальные блоки памяти, что позволяет быстро выполнять операции на уровне машинного кода и эффективно использовать память.